/** Parity suite: the TypeScript engine must reproduce the Python
 * rankloop 0.2 outputs recorded in fixtures/parity.json (generated by
 * tools/gen-parity-fixtures.py against the real reference implementation).
 *
 * If a test here fails, the port drifted — fix the port, or, when the
 * change is deliberate, regenerate the fixtures in the same commit. */

import { describe, expect, it } from "vitest";
import fx from "./fixtures/parity.json";
import {
  classify, computeQuota, llmsFull, llmsTxt, manifest, relevant, renderBrief,
  rss, score, sitemap, slugify, validate,
  type CorpusEntry, type EngineConfig, type KeywordRow, type SerpData,
} from "../src/index.ts";

const cfgMd = fx.configMd as unknown as EngineConfig;
const cfgHtml = fx.configHtml as unknown as EngineConfig;

function corpusEntries(name: keyof typeof fx.corpora): CorpusEntry[] {
  const corpus = fx.corpora[name] as { mode: string; files: Record<string, string> };
  return Object.entries(corpus.files).map(([file, raw]) => ({
    slug: corpus.mode === "markdown" ? file.replace(/\.md$/, "") : file.split("/")[0]!,
    raw,
  }));
}

describe("score()", () => {
  it("matches the Python scorer across the fixture grid", () => {
    for (const c of fx.score) {
      expect(
        score(c.volume, c.difficulty, c.intent),
        `score(${c.volume}, ${c.difficulty}, ${c.intent})`,
      ).toBeCloseTo(c.expected, 9);
    }
  });
});

describe("slugify()", () => {
  it("matches the Python slugifier", () => {
    for (const c of fx.slugify) {
      expect(slugify(c.input), JSON.stringify(c.input)).toBe(c.expected);
    }
  });
});

describe("relevant()", () => {
  it("applies the same negative-veto-then-positive gate", () => {
    for (const c of fx.relevant) {
      expect(relevant(cfgMd, c.kw), c.kw).toBe(c.ok);
    }
  });
});

describe("classify()", () => {
  it("matches the built-in rules", () => {
    for (const c of fx.classify.base) {
      expect(classify(cfgMd, c.kw), c.kw).toEqual([c.category, c.format]);
    }
  });

  it("site-authored rules run first, with the same fallbacks", () => {
    const cfg: EngineConfig = {
      ...cfgMd,
      keywords: { ...cfgMd.keywords, classify: fx.classify.withRules.rules },
    };
    for (const c of fx.classify.withRules.cases) {
      expect(classify(cfg, c.kw), c.kw).toEqual([c.category, c.format]);
    }
  });
});

describe("computeQuota()", () => {
  it("matches catch-up semantics including caps, gaps and edge dates", () => {
    for (const c of fx.quota) {
      const got = computeQuota(
        { startDate: c.startDate, postsPerDay: c.postsPerDay, catchupCap: c.catchupCap },
        c.publishedDates,
        c.today,
      );
      expect(got, `start=${c.startDate}`).toBe(c.expected);
    }
  });
});

describe("laws / validate()", () => {
  it("green corpus stays green", () => {
    const posts = manifest(cfgMd, corpusEntries("good"));
    expect(validate(cfgMd, posts).map((p) => [p.slug, p.law])).toEqual(fx.laws.good);
  });

  it("failing corpus fails the same laws in the same order", () => {
    const posts = manifest(cfgMd, corpusEntries("fail"));
    expect(validate(cfgMd, posts).map((p) => [p.slug, p.law])).toEqual(fx.laws.fail);
  });

  it("html corpus parses and passes identically", () => {
    const posts = manifest(cfgHtml, corpusEntries("html"));
    expect(validate(cfgHtml, posts).map((p) => [p.slug, p.law])).toEqual(fx.laws.html);
    const p = posts[0]!;
    expect({
      slug: p.slug, title: p.title, description: p.description, date: p.date,
      category: p.category, wordCount: p.wordCount, keyword: p.keyword, minutes: p.minutes,
    }).toEqual(fx.htmlPost);
  });
});

describe("renderBrief()", () => {
  const posts = () => manifest(cfgMd, corpusEntries("wire"));

  it("reproduces the Python brief byte-for-byte", () => {
    const got = renderBrief({
      cfg: cfgMd,
      row: fx.brief.row as KeywordRow,
      category: fx.brief.category,
      posts: posts(),
      serp: fx.brief.serp as SerpData,
      today: fx.brief.today,
    });
    expect(got).toBe(fx.brief.markdown);
  });

  it("reproduces the no-SERP fallback brief", () => {
    const got = renderBrief({
      cfg: cfgMd,
      row: fx.brief.row as KeywordRow,
      category: fx.brief.category,
      posts: posts(),
      serp: null,
      today: fx.brief.today,
    });
    expect(got).toBe(fx.brief.markdownNoSerp);
  });
});

describe("wire artifacts", () => {
  const posts = () => manifest(cfgMd, corpusEntries("wire"));

  it("sitemap.xml matches", () => {
    expect(sitemap(cfgMd, posts(), { today: fx.brief.today })).toBe(fx.wire.sitemap);
  });

  it("rss.xml matches", () => {
    expect(rss(cfgMd, posts())).toBe(fx.wire.rss);
  });

  it("llms.txt matches", () => {
    expect(llmsTxt(cfgMd, posts())).toBe(fx.wire.llmsTxt);
  });

  it("llms-full.txt matches (markdown mode)", () => {
    expect(llmsFull(cfgMd, posts())).toBe(fx.wire.llmsFull);
  });

  it("llms-full.txt matches (html mode article walker)", () => {
    const posts = manifest(cfgHtml, corpusEntries("html"));
    expect(llmsFull(cfgHtml, posts)).toBe(fx.wire.htmlLlmsFull);
  });
});
