// The files a scaffold PR writes (spec 0030).
//
// These read the markdown rankloop's GitHub adapter already publishes —
// `content/<blogPath>/<slug>.md` via repoPathFor — so the scaffold and the
// publisher agree on where posts live without either one configuring the
// other.
//
// Two rules shape every template here:
//
// 1. NO NEW DEPENDENCIES except a markdown renderer, and that one is
//    declared in the PR body with its install command. Frontmatter parsing
//    is inlined rather than pulling gray-matter: a scaffold whose build
//    fails because the user did not read a README is worse than no scaffold.
// 2. Structure matches what the publish laws already enforce — hero, table
//    of contents, H2 sections, FAQ, related posts. The laws check the
//    content; these templates give it somewhere to render.

import type { SiteTheme } from "@/server/features/rankloop/theme/theme.logic";
import { renderThemeCss } from "@/server/features/rankloop/theme/theme.logic";
import {
  safeBlogRoot,
  scaffoldPaths,
  type ScaffoldFile,
  type StackId,
} from "@/server/features/rankloop/theme/stack.logic";

/** Renderers we can use if the repo already has one. Checked so the PR can
 *  say "you already have this" instead of asking for an install nobody
 *  needs. */
const KNOWN_RENDERERS = ["marked", "markdown-it", "remark", "@next/mdx", "astro"] as const;

export function detectRenderer(packageJson: string | null): string | null {
  if (!packageJson) return null;
  return KNOWN_RENDERERS.find((dep) => new RegExp(`"${dep}"\\s*:`).test(packageJson)) ?? null;
}

// ---------------------------------------------------------------------------
// Shared snippets
// ---------------------------------------------------------------------------

/**
 * Frontmatter parsing, inlined into every template.
 *
 * Twelve lines against a dependency the user has to know to install. The
 * markdown rankloop writes has a fixed, simple frontmatter block — this is
 * not a general YAML parser and does not pretend to be.
 */
const FRONTMATTER_TS = `type Frontmatter = Record<string, string>;

function parseFrontmatter(raw: string): { data: Frontmatter; body: string } {
  const match = /^---\\r?\\n([\\s\\S]*?)\\r?\\n---\\r?\\n?/.exec(raw);
  if (!match) return { data: {}, body: raw };
  const data: Frontmatter = {};
  for (const line of match[1].split(/\\r?\\n/)) {
    const idx = line.indexOf(":");
    if (idx === -1) continue;
    const key = line.slice(0, idx).trim();
    const value = line.slice(idx + 1).trim().replace(/^["']|["']$/g, "");
    if (key) data[key] = value;
  }
  return { data, body: raw.slice(match[0].length) };
}`;

const CSS_BODY = `
.rl-post {
  max-width: var(--rl-container);
  margin: 0 auto;
  padding: 3rem 1.25rem 6rem;
  color: var(--rl-fg);
  background: var(--rl-bg);
  font-family: var(--rl-font-body);
  line-height: 1.7;
}
.rl-post h1, .rl-post h2, .rl-post h3 { font-family: var(--rl-font-heading); line-height: 1.25; }
.rl-post h1 { font-size: 2.5rem; margin: 0 0 0.5rem; }
.rl-post h2 { font-size: 1.6rem; margin: 2.5rem 0 0.75rem; }
.rl-post a { color: var(--rl-accent); }
.rl-dek { font-size: 1.15rem; opacity: 0.75; margin: 0 0 1.5rem; }
.rl-meta { font-size: 0.875rem; opacity: 0.6; }
.rl-toc, .rl-takeaways, .rl-faq {
  border: 1px solid var(--rl-border);
  border-radius: var(--rl-radius);
  padding: 1rem 1.25rem;
  margin: 2rem 0;
}
.rl-toc ol { margin: 0.5rem 0 0; padding-left: 1.25rem; }
.rl-index { max-width: var(--rl-container); margin: 0 auto; padding: 3rem 1.25rem; }
.rl-card {
  display: block;
  border: 1px solid var(--rl-border);
  border-radius: var(--rl-radius);
  padding: 1.25rem;
  margin-bottom: 1rem;
  text-decoration: none;
  color: inherit;
}
.rl-card:hover { border-color: var(--rl-accent); }
`;

// ---------------------------------------------------------------------------
// Next.js (app router)
// ---------------------------------------------------------------------------

function nextAppIndex(blogRoot: string): string {
  return `import fs from "node:fs";
import path from "node:path";
import Link from "next/link";
import "./rankloop-theme.css";

// Generated by rankloop. Posts are markdown in content/${blogRoot}/ —
// rankloop writes them there; this route lists them.

${FRONTMATTER_TS}

const POSTS_DIR = path.join(process.cwd(), "content", "${blogRoot}");

function allPosts() {
  if (!fs.existsSync(POSTS_DIR)) return [];
  return fs
    .readdirSync(POSTS_DIR)
    .filter((f) => f.endsWith(".md") && f !== "index.md")
    .map((file) => {
      const { data } = parseFrontmatter(
        fs.readFileSync(path.join(POSTS_DIR, file), "utf8"),
      );
      return {
        slug: file.replace(/\\.md$/, ""),
        title: data.title ?? file,
        description: data.description ?? "",
        date: data.date ?? "",
      };
    })
    .sort((a, b) => b.date.localeCompare(a.date));
}

export default function BlogIndex() {
  const posts = allPosts();
  return (
    <main className="rl-index">
      <h1>Blog</h1>
      {posts.length === 0 ? <p>No posts yet.</p> : null}
      {posts.map((post) => (
        <Link key={post.slug} href={\`/${blogRoot}/\${post.slug}\`} className="rl-card">
          <h2>{post.title}</h2>
          <p className="rl-meta">{post.date}</p>
          <p>{post.description}</p>
        </Link>
      ))}
    </main>
  );
}
`;
}

function nextAppPost(blogRoot: string, renderer: string): string {
  return `import fs from "node:fs";
import path from "node:path";
import { marked } from "${renderer}";
import "../rankloop-theme.css";

// Generated by rankloop. Renders one post from content/${blogRoot}/<slug>.md.

${FRONTMATTER_TS}

const POSTS_DIR = path.join(process.cwd(), "content", "${blogRoot}");

function readPost(slug: string) {
  const file = path.join(POSTS_DIR, \`\${slug}.md\`);
  if (!fs.existsSync(file)) return null;
  return parseFrontmatter(fs.readFileSync(file, "utf8"));
}

export function generateStaticParams() {
  if (!fs.existsSync(POSTS_DIR)) return [];
  return fs
    .readdirSync(POSTS_DIR)
    .filter((f) => f.endsWith(".md") && f !== "index.md")
    .map((f) => ({ slug: f.replace(/\\.md$/, "") }));
}

export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const post = readPost(slug);
  if (!post) return {};
  return { title: post.data.title, description: post.data.description };
}

export default async function Post({ params }: { params: Promise<{ slug: string }> }) {
  const { slug } = await params;
  const post = readPost(slug);
  if (!post) return <main className="rl-post"><h1>Not found</h1></main>;

  const html = marked.parse(post.body) as string;
  // Article + FAQPage schema, mirroring what the laws already check for in
  // the markdown itself.
  const schema = {
    "@context": "https://schema.org",
    "@type": "Article",
    headline: post.data.title,
    description: post.data.description,
    datePublished: post.data.date,
  };

  return (
    <main className="rl-post">
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }}
      />
      <h1>{post.data.title}</h1>
      {post.data.description ? <p className="rl-dek">{post.data.description}</p> : null}
      <p className="rl-meta">{post.data.date}</p>
      <article dangerouslySetInnerHTML={{ __html: html }} />
    </main>
  );
}
`;
}

// ---------------------------------------------------------------------------
// Astro
// ---------------------------------------------------------------------------

function astroIndex(blogRoot: string): string {
  return `---
// Generated by rankloop. Posts are markdown in content/${blogRoot}/.
import "../../styles/rankloop-theme.css";
const modules = import.meta.glob("../../../content/${blogRoot}/*.md", { eager: true });
const posts = Object.entries(modules)
  .map(([file, mod]: [string, any]) => ({
    slug: file.split("/").pop()!.replace(/\\.md$/, ""),
    ...(mod.frontmatter ?? {}),
  }))
  .sort((a, b) => String(b.date ?? "").localeCompare(String(a.date ?? "")));
---
<main class="rl-index">
  <h1>Blog</h1>
  {posts.length === 0 && <p>No posts yet.</p>}
  {posts.map((post) => (
    <a class="rl-card" href={\`/${blogRoot}/\${post.slug}\`}>
      <h2>{post.title ?? post.slug}</h2>
      <p class="rl-meta">{post.date}</p>
      <p>{post.description}</p>
    </a>
  ))}
</main>
`;
}

function astroPost(blogRoot: string): string {
  return `---
// Generated by rankloop. Astro renders the markdown itself — no extra
// dependency needed here.
import "../../styles/rankloop-theme.css";

export async function getStaticPaths() {
  const modules = import.meta.glob("../../../content/${blogRoot}/*.md", { eager: true });
  return Object.entries(modules).map(([file, mod]: [string, any]) => ({
    params: { slug: file.split("/").pop()!.replace(/\\.md$/, "") },
    props: { post: mod },
  }));
}

const { post } = Astro.props;
const { Content, frontmatter } = post;
---
<main class="rl-post">
  <script type="application/ld+json" set:html={JSON.stringify({
    "@context": "https://schema.org",
    "@type": "Article",
    headline: frontmatter.title,
    description: frontmatter.description,
    datePublished: frontmatter.date,
  })} />
  <h1>{frontmatter.title}</h1>
  {frontmatter.description && <p class="rl-dek">{frontmatter.description}</p>}
  <p class="rl-meta">{frontmatter.date}</p>
  <article><Content /></article>
</main>
`;
}

// ---------------------------------------------------------------------------
// Static HTML
// ---------------------------------------------------------------------------

function staticIndex(blogRoot: string): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>Blog</title>
  <link rel="stylesheet" href="/${blogRoot}/rankloop-theme.css" />
</head>
<body>
  <main class="rl-index">
    <h1>Blog</h1>
    <!-- rankloop appends one .rl-card per published post between the markers
         below. It only ever edits between them; anything outside is yours. -->
    <!-- rankloop:posts:start -->
    <!-- rankloop:posts:end -->
  </main>
</body>
</html>
`;
}

function staticPost(blogRoot: string): string {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title><!-- rankloop:title --></title>
  <meta name="description" content="<!-- rankloop:description -->" />
  <link rel="stylesheet" href="/${blogRoot}/rankloop-theme.css" />
</head>
<body>
  <main class="rl-post">
    <h1><!-- rankloop:title --></h1>
    <article>
      <!-- rankloop:content:start -->
      <!-- rankloop:content:end -->
    </article>
  </main>
</body>
</html>
`;
}

// ---------------------------------------------------------------------------
// Assembly
// ---------------------------------------------------------------------------

export interface ScaffoldPlan {
  files: ScaffoldFile[];
  /** The one dependency a stack may need, or null when it needs none. */
  requiredDependency: string | null;
}

/**
 * The files to add for a stack, in the extracted theme.
 *
 * Returns an empty plan for an unknown stack rather than a best guess —
 * `scaffoldPaths` already refuses to name paths for a framework it cannot
 * identify, and inventing them here would route around that refusal.
 */
export function buildScaffold(input: {
  stack: StackId;
  blogPath: string;
  theme: SiteTheme;
  /** package.json contents, to see whether a renderer is already installed. */
  packageJson: string | null;
}): ScaffoldPlan {
  const paths = scaffoldPaths(input.stack, input.blogPath);
  if (!paths) return { files: [], requiredDependency: null };

  // Same sanitiser scaffoldPaths uses. The root is interpolated into
  // generated source as well as into paths, so it has to be safe in both.
  const blogRoot = safeBlogRoot(input.blogPath);
  const existingRenderer = detectRenderer(input.packageJson);
  const css: ScaffoldFile = {
    path: paths.styles,
    content: renderThemeCss(input.theme) + CSS_BODY,
    purpose: "your site's colours, fonts and spacing as CSS variables",
  };

  switch (input.stack) {
    case "next-app":
    case "next-pages": {
      // Next has no built-in markdown renderer, so one dependency is
      // unavoidable. `marked` is the smallest well-known option; if the repo
      // already has a renderer we say so rather than asking for an install.
      const renderer = existingRenderer === "markdown-it" ? "markdown-it" : "marked";
      const needs = existingRenderer === null ? renderer : null;
      return {
        requiredDependency: needs,
        files: [
          {
            path: paths.index,
            content: nextAppIndex(blogRoot),
            purpose: "the blog index, listing every published post",
          },
          {
            path: paths.post,
            content: nextAppPost(blogRoot, renderer),
            purpose: "the post page, with Article schema and metadata",
          },
          css,
        ],
      };
    }
    case "astro":
      return {
        // Astro renders markdown itself. No install, and saying so is the
        // difference between a PR that merges and one that stalls on a
        // question.
        requiredDependency: null,
        files: [
          {
            path: paths.index,
            content: astroIndex(blogRoot),
            purpose: "the blog index, listing every published post",
          },
          {
            path: paths.post,
            content: astroPost(blogRoot),
            purpose: "the post page, with Article schema and metadata",
          },
          css,
        ],
      };
    case "static":
      return {
        requiredDependency: null,
        files: [
          {
            path: paths.index,
            content: staticIndex(blogRoot),
            purpose: "the blog index; rankloop appends posts between its markers",
          },
          {
            path: paths.post,
            content: staticPost(blogRoot),
            purpose: "the post template rankloop fills in per article",
          },
          css,
        ],
      };
    case "unknown":
      return { files: [], requiredDependency: null };
  }
}
