import { llmsFull, llmsTxt, rss, sitemap } from "@rankloop/engine";
import type { EngineConfig, Post } from "@rankloop/engine";
import type { DerivedArtifact } from "./types";

// The derived artifacts, regenerated whole from the corpus manifest by the
// engine's own wire module (spec 0021, step 6).
//
// This runs for the GitHub target and nowhere else. On WordPress and on a
// webhook site, sitemap.xml is generated by the user's plugin or their build,
// and overwriting it would be rankloop taking ownership of a file it was never
// given. In a repo rankloop commits to, these four files are ours: the engine
// regenerates them in full every time, so there is no splice state to corrupt
// and a re-run is a no-op diff.

/** A content_pages row, in the fields the wire artifacts actually read. */
export type WirePage = {
  /** Site-relative, with leading and trailing slashes ("/blog/foo/"). */
  path: string;
  title: string;
  description: string;
  /** YYYY-MM-DD. */
  date: string;
  /** Display category, matched against the engine config's taxonomy. */
  category: string;
};

/**
 * How many post bodies llms-full.txt is worth fetching.
 *
 * sitemap.xml, rss.xml and llms.txt need only what the manifest already
 * stores. llms-full.txt is the full text of every post, and the manifest does
 * not keep bodies — so it costs one GitHub read per post. At 300 posts that is
 * 300 of an hour's 5000 requests for one publish, which is the point where the
 * file stops being worth its price and rankloop says so instead of quietly
 * spending the budget.
 */
const MAX_FULL_TEXT_POSTS = 300;

function blogRootOf(config: EngineConfig): string {
  return `/${config.site.blogPath.replace(/^\/+|\/+$/g, "")}/`;
}

/**
 * The manifest as the engine models a corpus: posts sitting directly under one
 * blog root, each identified by its slug.
 *
 * A page outside that root is left out rather than given an invented URL. The
 * engine computes every `<loc>` as blogRoot + slug, so a page at "/docs/x/"
 * would be listed at "/blog/x/" — a sitemap entry pointing at a 404 is worse
 * than an absent one, and the note tells the user which pages their own build
 * still owns.
 */
export function corpusFromManifest(
  config: EngineConfig,
  manifest: WirePage[],
): { posts: Post[]; outsideBlogRoot: WirePage[] } {
  const root = blogRootOf(config);
  const posts: Post[] = [];
  const outsideBlogRoot: WirePage[] = [];
  for (const page of manifest) {
    const rest = page.path.startsWith(root)
      ? page.path.slice(root.length).replace(/\/+$/, "")
      : null;
    if (rest === null || rest === "" || rest.includes("/")) {
      outsideBlogRoot.push(page);
      continue;
    }
    posts.push({
      slug: rest,
      title: page.title,
      description: page.description,
      date: page.date,
      category: page.category,
      // Filled in below for llms-full.txt only; the other three artifacts
      // never read it.
      raw: "",
      wordCount: 0,
      keyword: null,
      minutes: 1,
    });
  }
  // Newest first is the order every wire function assumes (it takes posts[0]
  // as the site's lastmod and the feed's lastBuildDate).
  posts.sort((a, b) => (a.date < b.date ? 1 : a.date > b.date ? -1 : 0));
  return { posts, outsideBlogRoot };
}

type BuildArtifactsInput = {
  config: EngineConfig;
  manifest: WirePage[];
  /** ISO date for the empty-corpus lastmod fallback. */
  today: string;
  /** Reads a post's markdown back from the target; null when it is gone. */
  loadMarkdown: (path: string) => Promise<string | null>;
};

export async function buildDerivedArtifacts(
  input: BuildArtifactsInput,
): Promise<{ artifacts: DerivedArtifact[]; notes: string[] }> {
  const { config, manifest, today } = input;
  const { posts, outsideBlogRoot } = corpusFromManifest(config, manifest);
  const notes: string[] = [];

  if (outsideBlogRoot.length > 0) {
    notes.push(
      `${outsideBlogRoot.length} page${outsideBlogRoot.length === 1 ? "" : "s"} sit outside ${blogRootOf(config)} and stay out of the regenerated sitemap. Your own build still owns those.`,
    );
  }

  const artifacts: DerivedArtifact[] = [
    { path: "/sitemap.xml", content: sitemap(config, posts, { today }) },
    { path: "/rss.xml", content: rss(config, posts) },
    { path: "/llms.txt", content: llmsTxt(config, posts) },
  ];

  if (posts.length > MAX_FULL_TEXT_POSTS) {
    notes.push(
      `llms-full.txt was skipped: ${posts.length} posts would cost ${posts.length} repo reads on every publish. Everything else regenerated.`,
    );
    return { artifacts, notes };
  }

  // Sequential on purpose. A burst of parallel reads against one repo is how
  // a token earns a secondary rate limit, and this runs once per publish.
  const withBodies: Post[] = [];
  let unreadable = 0;
  for (const post of posts) {
    const markdown = await input.loadMarkdown(
      `/${config.site.blogPath.replace(/^\/+|\/+$/g, "")}/${post.slug}/`,
    );
    if (markdown === null) {
      unreadable += 1;
      continue;
    }
    withBodies.push({ ...post, raw: markdown });
  }
  if (unreadable > 0) {
    notes.push(
      `llms-full.txt covers ${withBodies.length} of ${posts.length} posts. rankloop couldn't read the rest out of the repo.`,
    );
  }
  artifacts.push({
    path: "/llms-full.txt",
    content: llmsFull(config, withBodies),
  });

  return { artifacts, notes };
}
