/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsAndConditionsRouteImport } from './routes/terms-and-conditions'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as MarketingRouteImport } from './routes/_marketing'
import { Route as GuidesIndexRouteImport } from './routes/guides/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as BlogsIndexRouteImport } from './routes/blogs/index'
import { Route as MarketingIndexRouteImport } from './routes/_marketing/index'
import { Route as JsScriptDotjsRouteImport } from './routes/js/script[.]js'
import { Route as GuidesSplatRouteImport } from './routes/guides/$'
import { Route as DocsSplatRouteImport } from './routes/docs/$'
import { Route as BlogsSplatRouteImport } from './routes/blogs/$'
import { Route as ApiSubscribeRouteImport } from './routes/api/subscribe'
import { Route as ApiEventRouteImport } from './routes/api/event'
import { Route as MarketingPricingRouteImport } from './routes/_marketing/pricing'
import { Route as MarketingOpenSourceSeoRouteImport } from './routes/_marketing/open-source-seo'
import { Route as MarketingGoogleSearchConsoleMcpRouteImport } from './routes/_marketing/google-search-console-mcp'
import { Route as MarketingFeaturesIndexRouteImport } from './routes/_marketing/features/index'
import { Route as MarketingFeaturesSiteAuditRouteImport } from './routes/_marketing/features/site-audit'
import { Route as MarketingFeaturesSavedKeywordsRouteImport } from './routes/_marketing/features/saved-keywords'
import { Route as MarketingFeaturesRankTrackingRouteImport } from './routes/_marketing/features/rank-tracking'
import { Route as MarketingFeaturesMcpRouteImport } from './routes/_marketing/features/mcp'
import { Route as MarketingFeaturesKeywordResearchRouteImport } from './routes/_marketing/features/keyword-research'
import { Route as MarketingFeaturesDomainOverviewRouteImport } from './routes/_marketing/features/domain-overview'
import { Route as MarketingFeaturesBacklinkCheckerRouteImport } from './routes/_marketing/features/backlink-checker'
import { Route as MarketingFeaturesAiSearchPromptsRouteImport } from './routes/_marketing/features/ai-search-prompts'
import { Route as MarketingFeaturesAiBrandVisibilityRouteImport } from './routes/_marketing/features/ai-brand-visibility'
import { Route as MarketingLibraryKeywordResearchIndexRouteImport } from './routes/_marketing/library/keyword-research/index'
import { Route as MarketingLibraryKeywordResearchSeedFromConversationRouteImport } from './routes/_marketing/library/keyword-research/seed-from-conversation'
import { Route as MarketingLibraryKeywordResearchSearchIntentMappingRouteImport } from './routes/_marketing/library/keyword-research/search-intent-mapping'
import { Route as MarketingLibraryKeywordResearchLongTailQuestionMiningRouteImport } from './routes/_marketing/library/keyword-research/long-tail-question-mining'
import { Route as MarketingLibraryKeywordResearchClusterTopicalHubsRouteImport } from './routes/_marketing/library/keyword-research/cluster-topical-hubs'

const TermsAndConditionsRoute = TermsAndConditionsRouteImport.update({
  id: '/terms-and-conditions',
  path: '/terms-and-conditions',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/_marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesIndexRoute = GuidesIndexRouteImport.update({
  id: '/guides/',
  path: '/guides/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsIndexRoute = BlogsIndexRouteImport.update({
  id: '/blogs/',
  path: '/blogs/',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingIndexRoute = MarketingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MarketingRoute,
} as any)
const JsScriptDotjsRoute = JsScriptDotjsRouteImport.update({
  id: '/js/script.js',
  path: '/js/script.js',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidesSplatRoute = GuidesSplatRouteImport.update({
  id: '/guides/$',
  path: '/guides/$',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsSplatRoute = DocsSplatRouteImport.update({
  id: '/docs/$',
  path: '/docs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogsSplatRoute = BlogsSplatRouteImport.update({
  id: '/blogs/$',
  path: '/blogs/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubscribeRoute = ApiSubscribeRouteImport.update({
  id: '/api/subscribe',
  path: '/api/subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventRoute = ApiEventRouteImport.update({
  id: '/api/event',
  path: '/api/event',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingPricingRoute = MarketingPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingOpenSourceSeoRoute = MarketingOpenSourceSeoRouteImport.update({
  id: '/open-source-seo',
  path: '/open-source-seo',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingGoogleSearchConsoleMcpRoute =
  MarketingGoogleSearchConsoleMcpRouteImport.update({
    id: '/google-search-console-mcp',
    path: '/google-search-console-mcp',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingFeaturesIndexRoute = MarketingFeaturesIndexRouteImport.update({
  id: '/features/',
  path: '/features/',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFeaturesSiteAuditRoute =
  MarketingFeaturesSiteAuditRouteImport.update({
    id: '/features/site-audit',
    path: '/features/site-audit',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingFeaturesSavedKeywordsRoute =
  MarketingFeaturesSavedKeywordsRouteImport.update({
    id: '/features/saved-keywords',
    path: '/features/saved-keywords',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingFeaturesRankTrackingRoute =
  MarketingFeaturesRankTrackingRouteImport.update({
    id: '/features/rank-tracking',
    path: '/features/rank-tracking',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingFeaturesMcpRoute = MarketingFeaturesMcpRouteImport.update({
  id: '/features/mcp',
  path: '/features/mcp',
  getParentRoute: () => MarketingRoute,
} as any)
const MarketingFeaturesKeywordResearchRoute =
  MarketingFeaturesKeywordResearchRouteImport.update({
    id: '/features/keyword-research',
    path: '/features/keyword-research',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingFeaturesDomainOverviewRoute =
  MarketingFeaturesDomainOverviewRouteImport.update({
    id: '/features/domain-overview',
    path: '/features/domain-overview',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingFeaturesBacklinkCheckerRoute =
  MarketingFeaturesBacklinkCheckerRouteImport.update({
    id: '/features/backlink-checker',
    path: '/features/backlink-checker',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingFeaturesAiSearchPromptsRoute =
  MarketingFeaturesAiSearchPromptsRouteImport.update({
    id: '/features/ai-search-prompts',
    path: '/features/ai-search-prompts',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingFeaturesAiBrandVisibilityRoute =
  MarketingFeaturesAiBrandVisibilityRouteImport.update({
    id: '/features/ai-brand-visibility',
    path: '/features/ai-brand-visibility',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingLibraryKeywordResearchIndexRoute =
  MarketingLibraryKeywordResearchIndexRouteImport.update({
    id: '/library/keyword-research/',
    path: '/library/keyword-research/',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingLibraryKeywordResearchSeedFromConversationRoute =
  MarketingLibraryKeywordResearchSeedFromConversationRouteImport.update({
    id: '/library/keyword-research/seed-from-conversation',
    path: '/library/keyword-research/seed-from-conversation',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingLibraryKeywordResearchSearchIntentMappingRoute =
  MarketingLibraryKeywordResearchSearchIntentMappingRouteImport.update({
    id: '/library/keyword-research/search-intent-mapping',
    path: '/library/keyword-research/search-intent-mapping',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingLibraryKeywordResearchLongTailQuestionMiningRoute =
  MarketingLibraryKeywordResearchLongTailQuestionMiningRouteImport.update({
    id: '/library/keyword-research/long-tail-question-mining',
    path: '/library/keyword-research/long-tail-question-mining',
    getParentRoute: () => MarketingRoute,
  } as any)
const MarketingLibraryKeywordResearchClusterTopicalHubsRoute =
  MarketingLibraryKeywordResearchClusterTopicalHubsRouteImport.update({
    id: '/library/keyword-research/cluster-topical-hubs',
    path: '/library/keyword-research/cluster-topical-hubs',
    getParentRoute: () => MarketingRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof MarketingIndexRoute
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/google-search-console-mcp': typeof MarketingGoogleSearchConsoleMcpRoute
  '/open-source-seo': typeof MarketingOpenSourceSeoRoute
  '/pricing': typeof MarketingPricingRoute
  '/api/event': typeof ApiEventRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/blogs/$': typeof BlogsSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/guides/$': typeof GuidesSplatRoute
  '/js/script.js': typeof JsScriptDotjsRoute
  '/blogs/': typeof BlogsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/features/ai-brand-visibility': typeof MarketingFeaturesAiBrandVisibilityRoute
  '/features/ai-search-prompts': typeof MarketingFeaturesAiSearchPromptsRoute
  '/features/backlink-checker': typeof MarketingFeaturesBacklinkCheckerRoute
  '/features/domain-overview': typeof MarketingFeaturesDomainOverviewRoute
  '/features/keyword-research': typeof MarketingFeaturesKeywordResearchRoute
  '/features/mcp': typeof MarketingFeaturesMcpRoute
  '/features/rank-tracking': typeof MarketingFeaturesRankTrackingRoute
  '/features/saved-keywords': typeof MarketingFeaturesSavedKeywordsRoute
  '/features/site-audit': typeof MarketingFeaturesSiteAuditRoute
  '/features/': typeof MarketingFeaturesIndexRoute
  '/library/keyword-research/cluster-topical-hubs': typeof MarketingLibraryKeywordResearchClusterTopicalHubsRoute
  '/library/keyword-research/long-tail-question-mining': typeof MarketingLibraryKeywordResearchLongTailQuestionMiningRoute
  '/library/keyword-research/search-intent-mapping': typeof MarketingLibraryKeywordResearchSearchIntentMappingRoute
  '/library/keyword-research/seed-from-conversation': typeof MarketingLibraryKeywordResearchSeedFromConversationRoute
  '/library/keyword-research/': typeof MarketingLibraryKeywordResearchIndexRoute
}
export interface FileRoutesByTo {
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/google-search-console-mcp': typeof MarketingGoogleSearchConsoleMcpRoute
  '/open-source-seo': typeof MarketingOpenSourceSeoRoute
  '/pricing': typeof MarketingPricingRoute
  '/api/event': typeof ApiEventRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/blogs/$': typeof BlogsSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/guides/$': typeof GuidesSplatRoute
  '/js/script.js': typeof JsScriptDotjsRoute
  '/': typeof MarketingIndexRoute
  '/blogs': typeof BlogsIndexRoute
  '/docs': typeof DocsIndexRoute
  '/guides': typeof GuidesIndexRoute
  '/features/ai-brand-visibility': typeof MarketingFeaturesAiBrandVisibilityRoute
  '/features/ai-search-prompts': typeof MarketingFeaturesAiSearchPromptsRoute
  '/features/backlink-checker': typeof MarketingFeaturesBacklinkCheckerRoute
  '/features/domain-overview': typeof MarketingFeaturesDomainOverviewRoute
  '/features/keyword-research': typeof MarketingFeaturesKeywordResearchRoute
  '/features/mcp': typeof MarketingFeaturesMcpRoute
  '/features/rank-tracking': typeof MarketingFeaturesRankTrackingRoute
  '/features/saved-keywords': typeof MarketingFeaturesSavedKeywordsRoute
  '/features/site-audit': typeof MarketingFeaturesSiteAuditRoute
  '/features': typeof MarketingFeaturesIndexRoute
  '/library/keyword-research/cluster-topical-hubs': typeof MarketingLibraryKeywordResearchClusterTopicalHubsRoute
  '/library/keyword-research/long-tail-question-mining': typeof MarketingLibraryKeywordResearchLongTailQuestionMiningRoute
  '/library/keyword-research/search-intent-mapping': typeof MarketingLibraryKeywordResearchSearchIntentMappingRoute
  '/library/keyword-research/seed-from-conversation': typeof MarketingLibraryKeywordResearchSeedFromConversationRoute
  '/library/keyword-research': typeof MarketingLibraryKeywordResearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_marketing': typeof MarketingRouteWithChildren
  '/privacy': typeof PrivacyRoute
  '/terms-and-conditions': typeof TermsAndConditionsRoute
  '/_marketing/google-search-console-mcp': typeof MarketingGoogleSearchConsoleMcpRoute
  '/_marketing/open-source-seo': typeof MarketingOpenSourceSeoRoute
  '/_marketing/pricing': typeof MarketingPricingRoute
  '/api/event': typeof ApiEventRoute
  '/api/subscribe': typeof ApiSubscribeRoute
  '/blogs/$': typeof BlogsSplatRoute
  '/docs/$': typeof DocsSplatRoute
  '/guides/$': typeof GuidesSplatRoute
  '/js/script.js': typeof JsScriptDotjsRoute
  '/_marketing/': typeof MarketingIndexRoute
  '/blogs/': typeof BlogsIndexRoute
  '/docs/': typeof DocsIndexRoute
  '/guides/': typeof GuidesIndexRoute
  '/_marketing/features/ai-brand-visibility': typeof MarketingFeaturesAiBrandVisibilityRoute
  '/_marketing/features/ai-search-prompts': typeof MarketingFeaturesAiSearchPromptsRoute
  '/_marketing/features/backlink-checker': typeof MarketingFeaturesBacklinkCheckerRoute
  '/_marketing/features/domain-overview': typeof MarketingFeaturesDomainOverviewRoute
  '/_marketing/features/keyword-research': typeof MarketingFeaturesKeywordResearchRoute
  '/_marketing/features/mcp': typeof MarketingFeaturesMcpRoute
  '/_marketing/features/rank-tracking': typeof MarketingFeaturesRankTrackingRoute
  '/_marketing/features/saved-keywords': typeof MarketingFeaturesSavedKeywordsRoute
  '/_marketing/features/site-audit': typeof MarketingFeaturesSiteAuditRoute
  '/_marketing/features/': typeof MarketingFeaturesIndexRoute
  '/_marketing/library/keyword-research/cluster-topical-hubs': typeof MarketingLibraryKeywordResearchClusterTopicalHubsRoute
  '/_marketing/library/keyword-research/long-tail-question-mining': typeof MarketingLibraryKeywordResearchLongTailQuestionMiningRoute
  '/_marketing/library/keyword-research/search-intent-mapping': typeof MarketingLibraryKeywordResearchSearchIntentMappingRoute
  '/_marketing/library/keyword-research/seed-from-conversation': typeof MarketingLibraryKeywordResearchSeedFromConversationRoute
  '/_marketing/library/keyword-research/': typeof MarketingLibraryKeywordResearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/privacy'
    | '/terms-and-conditions'
    | '/google-search-console-mcp'
    | '/open-source-seo'
    | '/pricing'
    | '/api/event'
    | '/api/subscribe'
    | '/blogs/$'
    | '/docs/$'
    | '/guides/$'
    | '/js/script.js'
    | '/blogs/'
    | '/docs/'
    | '/guides/'
    | '/features/ai-brand-visibility'
    | '/features/ai-search-prompts'
    | '/features/backlink-checker'
    | '/features/domain-overview'
    | '/features/keyword-research'
    | '/features/mcp'
    | '/features/rank-tracking'
    | '/features/saved-keywords'
    | '/features/site-audit'
    | '/features/'
    | '/library/keyword-research/cluster-topical-hubs'
    | '/library/keyword-research/long-tail-question-mining'
    | '/library/keyword-research/search-intent-mapping'
    | '/library/keyword-research/seed-from-conversation'
    | '/library/keyword-research/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/privacy'
    | '/terms-and-conditions'
    | '/google-search-console-mcp'
    | '/open-source-seo'
    | '/pricing'
    | '/api/event'
    | '/api/subscribe'
    | '/blogs/$'
    | '/docs/$'
    | '/guides/$'
    | '/js/script.js'
    | '/'
    | '/blogs'
    | '/docs'
    | '/guides'
    | '/features/ai-brand-visibility'
    | '/features/ai-search-prompts'
    | '/features/backlink-checker'
    | '/features/domain-overview'
    | '/features/keyword-research'
    | '/features/mcp'
    | '/features/rank-tracking'
    | '/features/saved-keywords'
    | '/features/site-audit'
    | '/features'
    | '/library/keyword-research/cluster-topical-hubs'
    | '/library/keyword-research/long-tail-question-mining'
    | '/library/keyword-research/search-intent-mapping'
    | '/library/keyword-research/seed-from-conversation'
    | '/library/keyword-research'
  id:
    | '__root__'
    | '/_marketing'
    | '/privacy'
    | '/terms-and-conditions'
    | '/_marketing/google-search-console-mcp'
    | '/_marketing/open-source-seo'
    | '/_marketing/pricing'
    | '/api/event'
    | '/api/subscribe'
    | '/blogs/$'
    | '/docs/$'
    | '/guides/$'
    | '/js/script.js'
    | '/_marketing/'
    | '/blogs/'
    | '/docs/'
    | '/guides/'
    | '/_marketing/features/ai-brand-visibility'
    | '/_marketing/features/ai-search-prompts'
    | '/_marketing/features/backlink-checker'
    | '/_marketing/features/domain-overview'
    | '/_marketing/features/keyword-research'
    | '/_marketing/features/mcp'
    | '/_marketing/features/rank-tracking'
    | '/_marketing/features/saved-keywords'
    | '/_marketing/features/site-audit'
    | '/_marketing/features/'
    | '/_marketing/library/keyword-research/cluster-topical-hubs'
    | '/_marketing/library/keyword-research/long-tail-question-mining'
    | '/_marketing/library/keyword-research/search-intent-mapping'
    | '/_marketing/library/keyword-research/seed-from-conversation'
    | '/_marketing/library/keyword-research/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  MarketingRoute: typeof MarketingRouteWithChildren
  PrivacyRoute: typeof PrivacyRoute
  TermsAndConditionsRoute: typeof TermsAndConditionsRoute
  ApiEventRoute: typeof ApiEventRoute
  ApiSubscribeRoute: typeof ApiSubscribeRoute
  BlogsSplatRoute: typeof BlogsSplatRoute
  DocsSplatRoute: typeof DocsSplatRoute
  GuidesSplatRoute: typeof GuidesSplatRoute
  JsScriptDotjsRoute: typeof JsScriptDotjsRoute
  BlogsIndexRoute: typeof BlogsIndexRoute
  DocsIndexRoute: typeof DocsIndexRoute
  GuidesIndexRoute: typeof GuidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms-and-conditions': {
      id: '/terms-and-conditions'
      path: '/terms-and-conditions'
      fullPath: '/terms-and-conditions'
      preLoaderRoute: typeof TermsAndConditionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing': {
      id: '/_marketing'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/': {
      id: '/guides/'
      path: '/guides'
      fullPath: '/guides/'
      preLoaderRoute: typeof GuidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/': {
      id: '/blogs/'
      path: '/blogs'
      fullPath: '/blogs/'
      preLoaderRoute: typeof BlogsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/': {
      id: '/_marketing/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof MarketingIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/js/script.js': {
      id: '/js/script.js'
      path: '/js/script.js'
      fullPath: '/js/script.js'
      preLoaderRoute: typeof JsScriptDotjsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guides/$': {
      id: '/guides/$'
      path: '/guides/$'
      fullPath: '/guides/$'
      preLoaderRoute: typeof GuidesSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/$': {
      id: '/docs/$'
      path: '/docs/$'
      fullPath: '/docs/$'
      preLoaderRoute: typeof DocsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blogs/$': {
      id: '/blogs/$'
      path: '/blogs/$'
      fullPath: '/blogs/$'
      preLoaderRoute: typeof BlogsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/subscribe': {
      id: '/api/subscribe'
      path: '/api/subscribe'
      fullPath: '/api/subscribe'
      preLoaderRoute: typeof ApiSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/event': {
      id: '/api/event'
      path: '/api/event'
      fullPath: '/api/event'
      preLoaderRoute: typeof ApiEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_marketing/pricing': {
      id: '/_marketing/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof MarketingPricingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/open-source-seo': {
      id: '/_marketing/open-source-seo'
      path: '/open-source-seo'
      fullPath: '/open-source-seo'
      preLoaderRoute: typeof MarketingOpenSourceSeoRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/google-search-console-mcp': {
      id: '/_marketing/google-search-console-mcp'
      path: '/google-search-console-mcp'
      fullPath: '/google-search-console-mcp'
      preLoaderRoute: typeof MarketingGoogleSearchConsoleMcpRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/': {
      id: '/_marketing/features/'
      path: '/features'
      fullPath: '/features/'
      preLoaderRoute: typeof MarketingFeaturesIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/site-audit': {
      id: '/_marketing/features/site-audit'
      path: '/features/site-audit'
      fullPath: '/features/site-audit'
      preLoaderRoute: typeof MarketingFeaturesSiteAuditRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/saved-keywords': {
      id: '/_marketing/features/saved-keywords'
      path: '/features/saved-keywords'
      fullPath: '/features/saved-keywords'
      preLoaderRoute: typeof MarketingFeaturesSavedKeywordsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/rank-tracking': {
      id: '/_marketing/features/rank-tracking'
      path: '/features/rank-tracking'
      fullPath: '/features/rank-tracking'
      preLoaderRoute: typeof MarketingFeaturesRankTrackingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/mcp': {
      id: '/_marketing/features/mcp'
      path: '/features/mcp'
      fullPath: '/features/mcp'
      preLoaderRoute: typeof MarketingFeaturesMcpRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/keyword-research': {
      id: '/_marketing/features/keyword-research'
      path: '/features/keyword-research'
      fullPath: '/features/keyword-research'
      preLoaderRoute: typeof MarketingFeaturesKeywordResearchRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/domain-overview': {
      id: '/_marketing/features/domain-overview'
      path: '/features/domain-overview'
      fullPath: '/features/domain-overview'
      preLoaderRoute: typeof MarketingFeaturesDomainOverviewRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/backlink-checker': {
      id: '/_marketing/features/backlink-checker'
      path: '/features/backlink-checker'
      fullPath: '/features/backlink-checker'
      preLoaderRoute: typeof MarketingFeaturesBacklinkCheckerRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/ai-search-prompts': {
      id: '/_marketing/features/ai-search-prompts'
      path: '/features/ai-search-prompts'
      fullPath: '/features/ai-search-prompts'
      preLoaderRoute: typeof MarketingFeaturesAiSearchPromptsRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/features/ai-brand-visibility': {
      id: '/_marketing/features/ai-brand-visibility'
      path: '/features/ai-brand-visibility'
      fullPath: '/features/ai-brand-visibility'
      preLoaderRoute: typeof MarketingFeaturesAiBrandVisibilityRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/library/keyword-research/': {
      id: '/_marketing/library/keyword-research/'
      path: '/library/keyword-research'
      fullPath: '/library/keyword-research/'
      preLoaderRoute: typeof MarketingLibraryKeywordResearchIndexRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/library/keyword-research/seed-from-conversation': {
      id: '/_marketing/library/keyword-research/seed-from-conversation'
      path: '/library/keyword-research/seed-from-conversation'
      fullPath: '/library/keyword-research/seed-from-conversation'
      preLoaderRoute: typeof MarketingLibraryKeywordResearchSeedFromConversationRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/library/keyword-research/search-intent-mapping': {
      id: '/_marketing/library/keyword-research/search-intent-mapping'
      path: '/library/keyword-research/search-intent-mapping'
      fullPath: '/library/keyword-research/search-intent-mapping'
      preLoaderRoute: typeof MarketingLibraryKeywordResearchSearchIntentMappingRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/library/keyword-research/long-tail-question-mining': {
      id: '/_marketing/library/keyword-research/long-tail-question-mining'
      path: '/library/keyword-research/long-tail-question-mining'
      fullPath: '/library/keyword-research/long-tail-question-mining'
      preLoaderRoute: typeof MarketingLibraryKeywordResearchLongTailQuestionMiningRouteImport
      parentRoute: typeof MarketingRoute
    }
    '/_marketing/library/keyword-research/cluster-topical-hubs': {
      id: '/_marketing/library/keyword-research/cluster-topical-hubs'
      path: '/library/keyword-research/cluster-topical-hubs'
      fullPath: '/library/keyword-research/cluster-topical-hubs'
      preLoaderRoute: typeof MarketingLibraryKeywordResearchClusterTopicalHubsRouteImport
      parentRoute: typeof MarketingRoute
    }
  }
}

interface MarketingRouteChildren {
  MarketingGoogleSearchConsoleMcpRoute: typeof MarketingGoogleSearchConsoleMcpRoute
  MarketingOpenSourceSeoRoute: typeof MarketingOpenSourceSeoRoute
  MarketingPricingRoute: typeof MarketingPricingRoute
  MarketingIndexRoute: typeof MarketingIndexRoute
  MarketingFeaturesAiBrandVisibilityRoute: typeof MarketingFeaturesAiBrandVisibilityRoute
  MarketingFeaturesAiSearchPromptsRoute: typeof MarketingFeaturesAiSearchPromptsRoute
  MarketingFeaturesBacklinkCheckerRoute: typeof MarketingFeaturesBacklinkCheckerRoute
  MarketingFeaturesDomainOverviewRoute: typeof MarketingFeaturesDomainOverviewRoute
  MarketingFeaturesKeywordResearchRoute: typeof MarketingFeaturesKeywordResearchRoute
  MarketingFeaturesMcpRoute: typeof MarketingFeaturesMcpRoute
  MarketingFeaturesRankTrackingRoute: typeof MarketingFeaturesRankTrackingRoute
  MarketingFeaturesSavedKeywordsRoute: typeof MarketingFeaturesSavedKeywordsRoute
  MarketingFeaturesSiteAuditRoute: typeof MarketingFeaturesSiteAuditRoute
  MarketingFeaturesIndexRoute: typeof MarketingFeaturesIndexRoute
  MarketingLibraryKeywordResearchClusterTopicalHubsRoute: typeof MarketingLibraryKeywordResearchClusterTopicalHubsRoute
  MarketingLibraryKeywordResearchLongTailQuestionMiningRoute: typeof MarketingLibraryKeywordResearchLongTailQuestionMiningRoute
  MarketingLibraryKeywordResearchSearchIntentMappingRoute: typeof MarketingLibraryKeywordResearchSearchIntentMappingRoute
  MarketingLibraryKeywordResearchSeedFromConversationRoute: typeof MarketingLibraryKeywordResearchSeedFromConversationRoute
  MarketingLibraryKeywordResearchIndexRoute: typeof MarketingLibraryKeywordResearchIndexRoute
}

const MarketingRouteChildren: MarketingRouteChildren = {
  MarketingGoogleSearchConsoleMcpRoute: MarketingGoogleSearchConsoleMcpRoute,
  MarketingOpenSourceSeoRoute: MarketingOpenSourceSeoRoute,
  MarketingPricingRoute: MarketingPricingRoute,
  MarketingIndexRoute: MarketingIndexRoute,
  MarketingFeaturesAiBrandVisibilityRoute:
    MarketingFeaturesAiBrandVisibilityRoute,
  MarketingFeaturesAiSearchPromptsRoute: MarketingFeaturesAiSearchPromptsRoute,
  MarketingFeaturesBacklinkCheckerRoute: MarketingFeaturesBacklinkCheckerRoute,
  MarketingFeaturesDomainOverviewRoute: MarketingFeaturesDomainOverviewRoute,
  MarketingFeaturesKeywordResearchRoute: MarketingFeaturesKeywordResearchRoute,
  MarketingFeaturesMcpRoute: MarketingFeaturesMcpRoute,
  MarketingFeaturesRankTrackingRoute: MarketingFeaturesRankTrackingRoute,
  MarketingFeaturesSavedKeywordsRoute: MarketingFeaturesSavedKeywordsRoute,
  MarketingFeaturesSiteAuditRoute: MarketingFeaturesSiteAuditRoute,
  MarketingFeaturesIndexRoute: MarketingFeaturesIndexRoute,
  MarketingLibraryKeywordResearchClusterTopicalHubsRoute:
    MarketingLibraryKeywordResearchClusterTopicalHubsRoute,
  MarketingLibraryKeywordResearchLongTailQuestionMiningRoute:
    MarketingLibraryKeywordResearchLongTailQuestionMiningRoute,
  MarketingLibraryKeywordResearchSearchIntentMappingRoute:
    MarketingLibraryKeywordResearchSearchIntentMappingRoute,
  MarketingLibraryKeywordResearchSeedFromConversationRoute:
    MarketingLibraryKeywordResearchSeedFromConversationRoute,
  MarketingLibraryKeywordResearchIndexRoute:
    MarketingLibraryKeywordResearchIndexRoute,
}

const MarketingRouteWithChildren = MarketingRoute._addFileChildren(
  MarketingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  MarketingRoute: MarketingRouteWithChildren,
  PrivacyRoute: PrivacyRoute,
  TermsAndConditionsRoute: TermsAndConditionsRoute,
  ApiEventRoute: ApiEventRoute,
  ApiSubscribeRoute: ApiSubscribeRoute,
  BlogsSplatRoute: BlogsSplatRoute,
  DocsSplatRoute: DocsSplatRoute,
  GuidesSplatRoute: GuidesSplatRoute,
  JsScriptDotjsRoute: JsScriptDotjsRoute,
  BlogsIndexRoute: BlogsIndexRoute,
  DocsIndexRoute: DocsIndexRoute,
  GuidesIndexRoute: GuidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
